version: '3'

services:
  waiter_node:
    image: node:latest
    working_dir: /app
    volumes:
      - ./customer:/app
      - ./waiter_dist:/app/dist
    command: sh -c "npm install && npm run build"
    restart: "no"
  waiter_customer:
    image: node:latest
    working_dir: /app
    volumes:
      - ./customer:/app
      - ./customer_dist:/app/dist
    command: sh -c "npm install && npm run build"
    restart: "no"
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./waiter_dist:/srv/waiter
      - ./customer_dist:/srv/customer
    depends_on:
      - waiter_node
      - waiter_customer
    restart: always
