version: '3'

services:
  node:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
      - ./dist:/app/dist
    command: sh -c "npm install && npm run build"
    restart: "no"
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/srv
    depends_on:
      - node
    restart: always
